default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>
  username: <%= ENV["PGUSER"] || ENV["USER"] %>
  password: <%= ENV["PGPASSWORD"] %>
  host: <%= ENV["PGHOST"] || "localhost" %>
  port: <%= ENV.fetch("PGPORT", 5433) %>

development:
  url: <%= ENV["DATABASE_URL"] || "postgres://postgres:password@127.0.0.1:5433/okirakuya_development" %>

test:
  <<: *default
  database: okirakuya_test

production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>   # Heroku はこれでOK
